// Menu data
const menu = [
  // Healthy dishes
  {id:1, name:"Tomato basil soup", cat:"healthy", price:12, img:"https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&auto=format&fit=crop", kcal:180, weight:"350g", time:"20 min", difficulty:"Easy", ingr:"Fresh tomatoes, basil, cream, onion, garlic", desc:"Light and warm soup for a cozy evening", protein: 8, vegetarian: true},
  {id:2, name:"Greek salad", cat:"healthy", price:14, img:"https://th.bing.com/th/id/OIP.lRe5FT01yrcDIdJ0F3qaEwHaE8?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3", kcal:250, weight:"300g", time:"15 min", difficulty:"Easy", ingr:"Tomatoes, cucumbers, olives, feta, onion, olive oil", desc:"Classic Mediterranean salad", protein: 12, vegetarian: true},
  {id:3, name:"Avocado toast with egg", cat:["healthy","breakfast"], price:11, img:"https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&auto=format&fit=crop", kcal:320, weight:"200g", time:"10 min", difficulty:"Easy", ingr:"Avocado, egg, whole grain bread, lemon juice", desc:"Perfect healthy breakfast", protein: 15, vegetarian: true},
  {id:4, name:"Quinoa with vegetables", cat:"healthy", price:15, img:"https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop", kcal:380, weight:"350g", time:"25 min", difficulty:"Medium", ingr:"Quinoa, broccoli, carrots, zucchini, olive oil", desc:"Hearty and healthy dish", protein: 18, vegetarian: true, vegan: true},
  {id:29, name:"Caesar salad", cat:"healthy", price:13, img:"https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500&auto=format&fit=crop", kcal:320, weight:"280g", time:"15 min", difficulty:"Easy", ingr:"Romaine lettuce, parmesan, croutons, caesar dressing", desc:"Classic Caesar salad with crispy croutons", protein: 14},
  {id:30, name:"Grilled chicken salad", cat:"healthy", price:16, img:"https://tse1.mm.bing.net/th/id/OIP.wwXXRcw7foBJJ30LUFgenwHaLH?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:380, weight:"350g", time:"25 min", difficulty:"Easy", ingr:"Grilled chicken, mixed greens, cherry tomatoes, balsamic", desc:"Fresh salad with tender grilled chicken", protein: 28},
  {id:31, name:"Buddha bowl", cat:"healthy", price:14, img:"https://th.bing.com/th/id/OIP.dI-1V0GwbVY1AktPIw3GtQHaHx?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3", kcal:420, weight:"400g", time:"20 min", difficulty:"Easy", ingr:"Brown rice, chickpeas, sweet potato, tahini", desc:"Colorful and nutritious bowl", protein: 16, vegetarian: true, vegan: true},
  
  // Spicy dishes
  {id:5, name:"Spicy ramen", cat:"spicy", price:18, img:"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop", kcal:520, weight:"450g", time:"30 min", difficulty:"Medium", ingr:"Noodles, beef, chili pepper, egg, green onion", desc:"Spicy ramen with meat and egg", protein: 25},
  {id:6, name:"Spicy chicken tacos", cat:"spicy", price:13, img:"https://th.bing.com/th/id/R.8a441cb9aaacf146010c57b532f7d691?rik=faN%2foQoRTo%2fIFg&riu=http%3a%2f%2fonestophalal.com%2fcdn%2fshop%2farticles%2fspicy_chicken_taco_recipe-1695929046510_800x.jpg%3fv%3d1695929739&ehk=ZtUO7LM2NmZ%2bhwtOqqEVMALQbQx94Qov%2bK%2ffGTdJduU%3d&risl=&pid=ImgRaw&r=0", kcal:350, weight:"250g", time:"20 min", difficulty:"Easy", ingr:"Chicken, tortilla, salsa, sour cream, hot sauce", desc:"Mexican tacos with chicken", protein: 22},
  {id:7, name:"Kimchi", cat:"spicy", price:8, img:"https://quiz.now/wp-content/uploads/2024/12/kimchi-quiz-1733921097.jpg", kcal:120, weight:"200g", time:"23 min", difficulty:"Hard", ingr:"Napa cabbage, chili pepper, garlic, ginger", desc:"Spicy Korean fermented side dish", protein: 5, vegetarian: true, vegan: true},
  {id:8, name:"Tofu curry", cat:["spicy","vegan"], price:16, img:"https://tse4.mm.bing.net/th/id/OIP.H1qhFJXt1gL1lTIxutV1CwHaLH?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:420, weight:"400g", time:"35 min", difficulty:"Medium", ingr:"Tofu, coconut milk, curry paste, vegetables", desc:"Spicy vegan curry", protein: 20, vegetarian: true, vegan: true},
  {id:32, name:"Buffalo wings", cat:"spicy", price:15, img:"https://th.bing.com/th/id/OIP.SCbeT5fdYksOgC3P4l_V3AHaE8?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3", kcal:450, weight:"300g", time:"25 min", difficulty:"Medium", ingr:"Chicken wings, buffalo sauce, blue cheese, celery", desc:"Crispy wings with spicy buffalo sauce", protein: 30},
  {id:33, name:"Jalapeño poppers", cat:"spicy", price:10, img:"https://th.bing.com/th/id/R.356d792842e0b0d43ea1acef42b38cbc?rik=DkadjzzsFdv0yA&pid=ImgRaw&r=0", kcal:280, weight:"200g", time:"20 min", difficulty:"Easy", ingr:"Jalapeños, cream cheese, breadcrumbs, spices", desc:"Spicy stuffed jalapeños", protein: 8, vegetarian: true},
  {id:34, name:"Pad Thai", cat:"spicy", price:17, img:"https://images.unsplash.com/photo-1559314809-0d155014e29e?w=500&auto=format&fit=crop", kcal:480, weight:"350g", time:"25 min", difficulty:"Medium", ingr:"Rice noodles, shrimp, bean sprouts, peanuts, lime", desc:"Classic Thai stir-fried noodles", protein: 22},
  
  // Sushi
  {id:9, name:"Philadelphia roll", cat:"sushi", price:16, img:"https://th.bing.com/th/id/R.f824ef63a066fbc2ac16e47cf242503b?rik=7pLq255ySWUv9A&pid=ImgRaw&r=0", kcal:320, weight:"250g", time:"25 min", difficulty:"Medium", ingr:"Salmon, cream cheese, rice, nori, cucumber", desc:"Japanese cuisine classic", protein: 18},
  {id:10, name:"California roll", cat:"sushi", price:14, img:"https://tse4.mm.bing.net/th/id/OIP.5iBu7ZYLEdWT52W8OXnLvAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:290, weight:"230g", time:"20 min", difficulty:"Medium", ingr:"Crab, avocado, cucumber, tobiko roe, rice", desc:"Popular crab roll", protein: 15},
  {id:11, name:"Salmon sashimi", cat:"sushi", price:22, img:"https://tse3.mm.bing.net/th/id/OIP.FD0ibDPgSu4cIfgCuYKb6gHaHa?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:220, weight:"180g", time:"15 min", difficulty:"Hard", ingr:"Fresh salmon, wasabi, soy sauce", desc:"Sliced fresh salmon", protein: 25},
  {id:12, name:"Tempura roll", cat:"sushi", price:17, img:"https://th.bing.com/th/id/OIP.sP2RZqRqAWewyDCdEgJ-0gHaE_?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3", kcal:380, weight:"270g", time:"30 min", difficulty:"Hard", ingr:"Tempura shrimp, avocado, unagi sauce", desc:"Crispy tempura roll", protein: 20},
  {id:35, name:"Dragon roll", cat:"sushi", price:19, img:"https://tse3.mm.bing.net/th/id/OIP.OFdIYo3XPaCW2gwbuW3SuQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:420, weight:"280g", time:"30 min", difficulty:"Hard", ingr:"Eel, cucumber, avocado, eel sauce, rice", desc:"Premium roll with grilled eel", protein: 24},
  {id:36, name:"Tuna nigiri", cat:"sushi", price:20, img:"https://tse4.mm.bing.net/th/id/OIP.QJ8t2KLgMXyaPkcfl-N18wHaHa?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:180, weight:"120g", time:"15 min", difficulty:"Hard", ingr:"Fresh tuna, sushi rice, wasabi", desc:"Premium tuna over sushi rice", protein: 28},
  {id:37, name:"Rainbow roll", cat:"sushi", price:18, img:"https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=500&auto=format&fit=crop", kcal:350, weight:"260g", time:"25 min", difficulty:"Medium", ingr:"Assorted fish, avocado, cucumber, rice", desc:"Colorful roll with mixed fish", protein: 20},
  
  // Pasta
  {id:13, name:"Carbonara", cat:"pasta", price:17, img:"https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=500&auto=format&fit=crop", kcal:580, weight:"350g", time:"25 min", difficulty:"Medium", ingr:"Spaghetti, bacon, cream, parmesan, egg", desc:"Italian pasta with bacon", protein: 28},
  {id:14, name:"Lasagna Bolognese", cat:"pasta", price:20, img:"https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=500&auto=format&fit=crop", kcal:650, weight:"400g", time:"45 min", difficulty:"Hard", ingr:"Lasagna sheets, ground meat, tomato sauce, cheese", desc:"Multi-layered Italian lasagna", protein: 32},
  {id:15, name:"Pesto pasta", cat:"pasta", price:15, img:"https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=500&auto=format&fit=crop", kcal:480, weight:"320g", time:"20 min", difficulty:"Easy", ingr:"Pasta, pesto sauce, pine nuts, parmesan", desc:"Aromatic pasta with pesto sauce", protein: 20, vegetarian: true},
  {id:16, name:"Fettuccine Alfredo", cat:"pasta", price:18, img:"https://th.bing.com/th/id/R.78a774b44a5673484d6160b6c610b5c7?rik=zoFJlVi9dw%2fX2w&pid=ImgRaw&r=0", kcal:520, weight:"350g", time:"30 min", difficulty:"Medium", ingr:"Fettuccine, cream sauce, chicken, parmesan", desc:"Creamy pasta with chicken", protein: 35},
  {id:38, name:"Spaghetti aglio e olio", cat:"pasta", price:13, img:"https://th.bing.com/th/id/R.14613c5a9b45d160c4780cfde22800e4?rik=p%2b9EDRNMjZh5Ug&pid=ImgRaw&r=0", kcal:420, weight:"300g", time:"15 min", difficulty:"Easy", ingr:"Spaghetti, garlic, olive oil, parsley, red pepper", desc:"Simple and delicious Italian classic", protein: 12, vegetarian: true, vegan: true},
  {id:39, name:"Penne arrabbiata", cat:"pasta", price:14, img:"https://tse2.mm.bing.net/th/id/OIP.e88Frv1MjRxT8kKwLEY7qgHaE8?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:450, weight:"320g", time:"20 min", difficulty:"Easy", ingr:"Penne, tomato sauce, garlic, red chili, parsley", desc:"Spicy tomato pasta", protein: 14, vegetarian: true, vegan: true},
  {id:40, name:"Ravioli with ricotta", cat:"pasta", price:16, img:"https://tse2.mm.bing.net/th/id/OIP.t_Z5bDj3Aivqn9sIa58iGQHaJ4?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:480, weight:"300g", time:"30 min", difficulty:"Medium", ingr:"Ravioli, ricotta cheese, spinach, butter sauce", desc:"Delicate pasta pockets with ricotta", protein: 18, vegetarian: true},
  
  // Vegan dishes
  {id:17, name:"Vegan bowl", cat:"vegan", price:14, img:"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&auto=format&fit=crop", kcal:420, weight:"400g", time:"20 min", difficulty:"Easy", ingr:"Quinoa, hummus, vegetables, avocado, seeds", desc:"Healthy and filling set", protein: 18, vegetarian: true, vegan: true},
  {id:18, name:"Tikka masala", cat:["vegan","spicy"], price:16, img:"https://th.bing.com/th/id/R.45c48ea17c74a9b49b51083fc410ac55?rik=n59mDrwCh1i07Q&pid=ImgRaw&r=0", kcal:480, weight:"380g", time:"40 min", difficulty:"Medium", ingr:"Coconut milk, spices, tofu, vegetables", desc:"Indian classic in vegan version", protein: 22, vegetarian: true, vegan: true},
  {id:19, name:"Vegan burgers", cat:"vegan", price:15, img:"https://th.bing.com/th/id/R.1eaec5d883647f7052ebb4ce53772cba?rik=XrbeBnnV8yovPw&pid=ImgRaw&r=0", kcal:450, weight:"300g", time:"30 min", difficulty:"Medium", ingr:"Black beans, beets, bun, vegetables", desc:"Juicy meat-free burgers", protein: 20, vegetarian: true, vegan: true},
  {id:20, name:"Mushroom steak", cat:"vegan", price:13, img:"https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?w=500&auto=format&fit=crop", kcal:280, weight:"250g", time:"25 min", difficulty:"Easy", ingr:"Portobello mushrooms, herbs, garlic, lemon", desc:"Portobello mushroom steak", protein: 15, vegetarian: true, vegan: true},
  {id:41, name:"Vegan pad thai", cat:["vegan","spicy"], price:15, img:"https://tse1.mm.bing.net/th/id/OIP.b-b-htvG4vhRlXahJj6VGwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:420, weight:"350g", time:"25 min", difficulty:"Medium", ingr:"Rice noodles, tofu, vegetables, tamarind sauce", desc:"Plant-based Thai noodles", protein: 18, vegetarian: true, vegan: true},
  {id:42, name:"Lentil curry", cat:["vegan","spicy"], price:14, img:"https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&auto=format&fit=crop", kcal:380, weight:"350g", time:"35 min", difficulty:"Medium", ingr:"Red lentils, coconut milk, curry spices, vegetables", desc:"Hearty lentil curry", protein: 20, vegetarian: true, vegan: true},
  {id:43, name:"Vegan pizza", cat:"vegan", price:16, img:"https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&auto=format&fit=crop", kcal:520, weight:"400g", time:"30 min", difficulty:"Medium", ingr:"Pizza dough, tomato sauce, vegan cheese, vegetables", desc:"Delicious plant-based pizza", protein: 16, vegetarian: true, vegan: true},
  
  // Desserts
  {id:21, name:"Tiramisu", cat:"dessert", price:12, img:"https://tse3.mm.bing.net/th/id/OIP.J__zr5QMc6p3voynKAnzbQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:420, weight:"200g", time:"30 min", difficulty:"Medium", ingr:"Mascarpone, coffee, ladyfingers, cocoa", desc:"Classic Italian dessert", protein: 8, vegetarian: true},
  {id:22, name:"New York cheesecake", cat:"dessert", price:14, img:"https://images.unsplash.com/photo-1578775887804-699de7086ff9?w=500&auto=format&fit=crop", kcal:450, weight:"220g", time:"60 min", difficulty:"Hard", ingr:"Cream cheese, cookies, cream, sugar", desc:"Famous New York cheesecake", protein: 10, vegetarian: true},
  {id:23, name:"Strawberry mousse", cat:"dessert", price:10, img:"https://hipstamama.ru/wp-content/uploads/2020/06/eggless-strawberry-mousse-690x1034.jpg", kcal:280, weight:"180g", time:"25 min", difficulty:"Medium", ingr:"Strawberries, cream, gelatin, sugar", desc:"Airy fruit dessert", protein: 6, vegetarian: true},
  {id:24, name:"Chocolate fondant", cat:"dessert", price:11, img:"https://tse3.mm.bing.net/th/id/OIP.Xe62S5zyHo677kkMlID2JgHaGn?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:380, weight:"150g", time:"20 min", difficulty:"Hard", ingr:"Dark chocolate, butter, eggs, flour", desc:"Chocolate dessert with liquid center", protein: 7, vegetarian: true},
  {id:44, name:"Chocolate lava cake", cat:"dessert", price:11, img:"https://tse4.mm.bing.net/th/id/OIP.-2P0ncfi4i35dpkiNgyumAHaLI?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:420, weight:"160g", time:"25 min", difficulty:"Hard", ingr:"Dark chocolate, butter, eggs, flour, vanilla", desc:"Warm chocolate cake with molten center", protein: 8, vegetarian: true},
  {id:45, name:"Apple pie", cat:"dessert", price:9, img:"https://th.bing.com/th/id/OIP.alxoF52zKgLFi5qFPv0ucQHaHU?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3", kcal:320, weight:"200g", time:"45 min", difficulty:"Medium", ingr:"Apples, pie crust, cinnamon, sugar, butter", desc:"Classic American apple pie", protein: 4, vegetarian: true},
  {id:46, name:"Ice cream sundae", cat:"dessert", price:8, img:"https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop", kcal:350, weight:"250g", time:"5 min", difficulty:"Easy", ingr:"Vanilla ice cream, chocolate sauce, whipped cream, cherry", desc:"Classic ice cream sundae", protein: 6, vegetarian: true},
  
  // Breakfast
  {id:25, name:"American pancakes", cat:"breakfast", price:11, img:"https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&auto=format&fit=crop", kcal:480, weight:"300g", time:"20 min", difficulty:"Easy", ingr:"Flour, eggs, milk, maple syrup", desc:"Fluffy pancakes with syrup", protein: 12, vegetarian: true},
  {id:26, name:"Smoothie bowl", cat:["breakfast","healthy"], price:10, img:"https://tse3.mm.bing.net/th/id/OIP.FlAczh7fqHhZu_uRCzLnRwHaLH?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:320, weight:"350g", time:"10 min", difficulty:"Easy", ingr:"Bananas, berries, oatmeal, nuts, honey", desc:"Healthy and bright breakfast", protein: 10, vegetarian: true, vegan: true},
  {id:27, name:"Vegetable omelet", cat:"breakfast", price:12, img:"https://tse3.mm.bing.net/th/id/OIP.o63tcSfmC77qZnkiAaWtLAHaLH?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:320, weight:"280g", time:"15 min", difficulty:"Easy", ingr:"Eggs, tomatoes, bell pepper, herbs", desc:"Hearty vegetable omelet", protein: 22, vegetarian: true},
  {id:28, name:"French toast", cat:"breakfast", price:9, img:"https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=500&auto=format&fit=crop", kcal:350, weight:"250g", time:"15 min", difficulty:"Easy", ingr:"Bread, eggs, milk, cinnamon, sugar", desc:"Sweet French-style toast", protein: 14, vegetarian: true},
  {id:47, name:"Eggs Benedict", cat:"breakfast", price:15, img:"https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&auto=format&fit=crop", kcal:520, weight:"300g", time:"25 min", difficulty:"Medium", ingr:"Poached eggs, English muffin, ham, hollandaise", desc:"Classic brunch favorite", protein: 24},
  {id:48, name:"Belgian waffles", cat:"breakfast", price:12, img:"https://th.bing.com/th/id/OIP.QMW30y0xZJIOHBZEyc2RqgHaHa?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3", kcal:450, weight:"280g", time:"20 min", difficulty:"Easy", ingr:"Waffle batter, butter, maple syrup, berries", desc:"Crispy Belgian-style waffles", protein: 10, vegetarian: true},
  {id:49, name:"Breakfast burrito", cat:"breakfast", price:13, img:"https://tse4.mm.bing.net/th/id/OIP.HekGeIc20HeCtHAk40NKdgHaFj?rs=1&pid=ImgDetMain&o=7&rm=3", kcal:480, weight:"350g", time:"20 min", difficulty:"Easy", ingr:"Tortilla, scrambled eggs, bacon, cheese, salsa", desc:"Hearty breakfast wrap", protein: 20},
];
